Repository PrafullRaj/Hactober2023, pull requests merged in 2023-10, with the labels that each got.

#1 Create Parity.java
  Computer Networks/Parity.java
Labels: hactoberfest-accepted

#2 Create fibonacci.java
  fibonacci.java
Labels: hacktoberfest-accepted

#3 Create 5digitreverse.java
  5digitreverse.java
Labels: hacktoberfest-accepted

#5 Create Astrologer_Foolu.java
  Astrologer_Foolu.java
Labels: hacktoberfest-accepted

#4 Create FCFS.java
  FCFS.java
Labels: hacktoberfest-accepted

#6 Create evenodd.c
  evenodd.c
Labels: hacktoberfest-accepted

#7 Create FactorialCode
  FactorialCode
Labels: hactoberfest-accepted, hacktoberfest-accepted

#9 Create radix_sort.java
  radix_sort.java
Labels: hacktoberfest-accepted

#10 Create Next Permutation.java
  Next Permutation.java
Labels: hacktoberfest-accepted

#11 adds bubbleSort.java
  BubbleSort.java
Labels: hacktoberfest-accepted

#16 Create Code
  DFS/Code
Labels: hacktoberfest-accepted

#15 Create swap.java
  swap.java
Labels: hacktoberfest-accepted

#13 Create Age_Calculator.java
  Age_Calculator.java
Labels: hacktoberfest-accepted

#17 Create Code_2
  DFS/Code_2
Labels: hacktoberfest-accepted

#19 Create Code_4
  DFS/Code_4
Labels: hacktoberfest-accepted

#18 Create Code_3
  DFS/Code_3
Labels: hacktoberfest-accepted

#28 Create Algo.c
  Algo.c
Labels: hacktoberfest-accepted

#27 Create Also.c
  Also.c
Labels: hacktoberfest-accepted

#25 Create LinkedList Operations
  LinkedList Operations
Labels: hacktoberfest-accepted

#29 Create Bfs.c
  Bfs.c
Labels: hacktoberfest-accepted

#31 Create KelvinToCelsiusConverter.java
  KelvinToCelsiusConverter.java
Labels: hacktoberfest-accepted

#30 Hacktober'23
  CountSort.java
Labels: hacktoberfest-accepted

#24 added mergeSort file
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  mergeSort.java
Labels: hacktoberfest-accepted

#23 Create BankManagementApp.java
  BankManagementApp.java
Labels: hacktoberfest-accepted

#22 CRC in Netcom
  Computer Networks/crc_client.py
  Computer Networks/crc_server.py
Labels: hacktoberfest-accepted

#21 Create longestCommonPrefix.java
  longestCommonPrefix.java
Labels: hacktoberfest-accepted

#20 C++ code added
  binarySearch.cpp
Labels: hacktoberfest-accepted

#36 Create a_algo.cpp
  a_algo.cpp
Labels: hacktoberfest-accepted

#34 Create DFS.java
  DFS.java
Labels: hacktoberfest-accepted

#33 Create BFS.java
  BFS.java
Labels: hacktoberfest-accepted

#32 Square root of a number using binary search in java (Hactober'23)
  rotateArrayToRightByK.java
  sqrt.java
Labels: hacktoberfest-accepted
